### ISSUE TITLE
Pictures for README.md

### ISSUE THREAD

**Issue by thepiyushway** [piyushsharma220699/automatedwhatsapp#1]
![reply](https://user-images.githubusercontent.com/45245975/91994219-fd8a7700-ed53-11ea-9666-c8c348adbb91.PNG)
![whatsapp_web](https://user-images.githubusercontent.com/45245975/91994399-30346f80-ed54-11ea-91a2-098d851ac10d.PNG)

**Comment by piyushsharma220699** [comment]
💯
