### ISSUE TITLE
Response from database?

### ISSUE THREAD

**Issue by piambak** [piyushsharma220699/automatedwhatsapp#3]
can the response is based on some database, like excel or spreadsheet maybe. so its basically using lookup formulas to search the response in the database. is it possible?

**Comment by thepiyushway** [comment]
Can you please elaborate on your question?
What this code will do is, open WhatsApp web after every 5 minutes(variable), search for the names that you've provided in the list, check if there is a green dot (which appears if you have an unread message), if there is one, then It will reply that person with the same!

**Comment by piambak** [comment]
umm sorry. never mind. I think that's concept is too far from your code
